replicaCount: 1
namespaceOverride: argocd
extraEnv:
  - name: AWS_REGION
    value: us-east-1
  - name: AWS_ROLE_SESSION_NAME
    value: cluster-name-argocd-image-updater

config:
  registries:
  - name: ECR
    api_url: https://059516066038.dkr.ecr.us-east-1.amazonaws.com
    prefix: 059516066038.dkr.ecr.us-east-1.amazonaws.com   # before v0.12 this needed to be set empty, prefix: ""
    default: true  # not supported before v0.12
    ping: yes
    insecure: no
    credentials: ext:/scripts/ecr-login.sh  #script name should match here and in authScripts 
    credsexpire: 11h
    tags:
      ignore:
        - latest
  git:
    user: CodeOps1891 # Replace with your GitHub username
    email: abdul.rehman@eurustechnologies.com # Replace with your email
    credentials: secret:argocd/argocd-image-updater-git
    

authScripts:
  enabled: true
  scripts: 
    ecr-login.sh: |   # notice script name matches above    
      #!/bin/sh
      aws ecr --region $AWS_REGION get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

# if using helm chart v0.10.0 or greater, then you need to allow read/write file system
securityContext:
  readOnlyRootFilesystem: false

extraEnv:
  - name: AWS_REGION
    value: "us-east-1"

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::059516066038:role/argocd-ecr-access
  name: "argocd-image-updater"  