apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing-system-dev
  namespace: argocd
  annotations:
    # ArgoCD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: ticketing=059516066038.dkr.ecr.us-east-1.amazonaws.com/ticketingsystem
    argocd-image-updater.argoproj.io/ticketing.update-strategy: newest-build
    argocd-image-updater.argoproj.io/ticketing.allow-tags: regexp:^[a-f0-9]{7,40}$
    argocd-image-updater.argoproj.io/ticketing.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/ticketing.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: values.yaml
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-repository: https://github.com/CodeOps1891/ArgoCD-Example.git
    argocd-image-updater.argoproj.io/git-commit-message: "build: automatic update of ticketing-system-dev image to {{.NewTag}}"


spec:
  project: default
  source:
    repoURL: https://github.com/CodeOps1891/ArgoCD-Example.git
    targetRevision: main
    path: ticketing
    helm:
      valueFiles:
        - ./values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
