---
# values-dev.yaml
image:
  repository: 059516066038.dkr.ecr.us-east-1.amazonaws.com/ticketingsystem
  tag: latest  # This will be updated automatically by ArgoCD Image Updater
  pullPolicy: Always

config:
  environment: dev
  namespace: backend
  serviceAccountName: adminaccess-backend

resources:
  requests:
    memory: "768Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "250m"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: backend
            operator: In
            values:
            - exists

nodeSelector: {}
tolerations: []

env:
  - name: DJANGO_SETTINGS_MODULE
    value: "ticketing_system.settings"
  - name: ENV
    value: "dev"

secret:
  - name: DATABASE_NAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_DATABASE_NAME
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_DATABASE_USER
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_DATABASE_PASSWORD
  - name: RABBITMQ_HOST
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_RABBITMQ_HOST
  - name: NO_SQL_HOST
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_NO_SQL_HOST
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_DATABASE_HOST
  - name: NO_SQL_ROUTER_NAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_NO_SQL_ROUTER_NAME
  - name: NO_SQL_DATABASE_NAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_NO_SQL_DATABASE_NAME
  - name: REPORTS_BUCKET
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_EXPORT_LOGS_BUCKET
  - name: ATTACHMENT_BUCKET
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_ATTACHMENT_BUCKET
  - name: IDP_URL
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_IDP_URL

imageUpdater:
enabled: true
strategy: newest-build
policy: major
---

# image:
#   repository: 059516066038.dkr.ecr.us-east-1.amazonaws.com/ticketingsystem
#   tag: latest
#   pullPolicy: Always

# config:
#   environment: dev
#   namespace: backend
#   serviceAccountName: adminaccess-backend

# resources:
#   requests:
#     memory: "768Mi"
#     cpu: "250m"
#   limits:
#     memory: "1024Mi"
#     cpu: "250m"

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#           - key: backend
#             operator: In
#             values:
#             - exists



# secret:
#   - name: DATABASE_NAME
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_DATABASE_NAME
#   - name: DATABASE_USER
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_DATABASE_USER
#   - name: DATABASE_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_DATABASE_PASSWORD
#   - name: RABBITMQ_HOST
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_RABBITMQ_HOST
#   - name: NO_SQL_HOST
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_NO_SQL_HOST
#   - name: DATABASE_HOST
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_DATABASE_HOST
#   - name: NO_SQL_ROUTER_NAME
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_NO_SQL_ROUTER_NAME
#   - name: NO_SQL_DATABASE_NAME
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_NO_SQL_DATABASE_NAME

#   - name: REPORTS_BUCKET
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_EXPORT_LOGS_BUCKET
#   - name: ATTACHMENT_BUCKET
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_ATTACHMENT_BUCKET
#   - name: IDP_URL
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_IDP_URL


# *****************************************************************

# secret:
# - name: DATABASE_USER
#   valueFrom:
#     secretKeyRef:
#       name: aws-secrets
#       key: LTSCALE_DEV_DATABASE_USER
# - name: DATABASE_PASSWORD
#   valueFrom:
#     secretKeyRef:
#       name: aws-secrets
#       key: LTSCALE_DEV_DATABASE_PASSWORD
# - name: RABBITMQ_HOST
#   valueFrom:
#     secretKeyRef:
#       name: aws-secrets
#       key: LTSCALE_DEV_RABBITMQ_HOST
# - name: NO_SQL_HOST
#   valueFrom:
#     secretKeyRef:
#       name: aws-secrets
#       key: LTSCALE_DEV_NO_SQL_HOST
# - name: DATABASE_NAME
#   value: "compliancexdb"
# - name: DATABASE_HOST
#   value: "10.0.4.21"
# - name: NO_SQL_ROUTER_NAME
#   value: "mongo_db"
# - name: NO_SQL_DATABASE_NAME
#   value: "compliancexdb"

# - name: REPORTS_BUCKET
#   value: "059516066038-export-logs-bucket"
# - name: ATTACHMENT_BUCKET
#   value: "059516066038-compliancex-ticketing-attachment"
# - name: IDP_URL
#   value: "https://idp.app.litmusscale.com"


# //**************************************


/*
---
image:
  repository: 059516066038.dkr.ecr.us-east-1.amazonaws.com/ticketingsystem
  tag: latest  # This will be updated automatically by ArgoCD Image Updater
  pullPolicy: Always

config:
  environment: dev
  namespace: backend
  serviceAccountName: adminaccess-backend

resources:
  requests:
    memory: "768Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "250m"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: backend
            operator: In
            values:
            - exists

nodeSelector: {}
tolerations: []

env:
  - name: DJANGO_SETTINGS_MODULE
    value: "ticketing_system.settings"
  - name: ENV
    value: "dev"

secret:
  - name: DATABASE_NAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_DATABASE_NAME
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_DATABASE_USER
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_DATABASE_PASSWORD
  - name: RABBITMQ_HOST
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_RABBITMQ_HOST
  - name: NO_SQL_HOST
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_NO_SQL_HOST
  - name: DATABASE_HOST
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_DATABASE_HOST
  - name: NO_SQL_ROUTER_NAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_NO_SQL_ROUTER_NAME
  - name: NO_SQL_DATABASE_NAME
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_NO_SQL_DATABASE_NAME
  - name: REPORTS_BUCKET
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_EXPORT_LOGS_BUCKET
  - name: ATTACHMENT_BUCKET
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_ATTACHMENT_BUCKET
  - name: IDP_URL
    valueFrom:
      secretKeyRef:
        name: aws-secrets
        key: SCALEOPS_IDP_URL
---

# image:
#   repository: 059516066038.dkr.ecr.us-east-1.amazonaws.com/ticketingsystem
#   tag: latest
#   pullPolicy: Always

# config:
#   environment: dev
#   namespace: backend
#   serviceAccountName: adminaccess-backend

# resources:
#   requests:
#     memory: "768Mi"
#     cpu: "250m"
#   limits:
#     memory: "1024Mi"
#     cpu: "250m"

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#           - key: backend
#             operator: In
#             values:
#             - exists



# secret:
#   - name: DATABASE_NAME
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_DATABASE_NAME
#   - name: DATABASE_USER
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_DATABASE_USER
#   - name: DATABASE_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_DATABASE_PASSWORD
#   - name: RABBITMQ_HOST
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_RABBITMQ_HOST
#   - name: NO_SQL_HOST
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_NO_SQL_HOST
#   - name: DATABASE_HOST
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_DATABASE_HOST
#   - name: NO_SQL_ROUTER_NAME
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_NO_SQL_ROUTER_NAME
#   - name: NO_SQL_DATABASE_NAME
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_NO_SQL_DATABASE_NAME

#   - name: REPORTS_BUCKET
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_EXPORT_LOGS_BUCKET
#   - name: ATTACHMENT_BUCKET
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_ATTACHMENT_BUCKET
#   - name: IDP_URL
#     valueFrom:
#       secretKeyRef:
#         name: aws-secrets
#         key: SCALEOPS_IDP_URL


# *****************************************************************

# secret:
# - name: DATABASE_USER
#   valueFrom:
#     secretKeyRef:
#       name: aws-secrets
#       key: LTSCALE_DEV_DATABASE_USER
# - name: DATABASE_PASSWORD
#   valueFrom:
#     secretKeyRef:
#       name: aws-secrets
#       key: LTSCALE_DEV_DATABASE_PASSWORD
# - name: RABBITMQ_HOST
#   valueFrom:
#     secretKeyRef:
#       name: aws-secrets
#       key: LTSCALE_DEV_RABBITMQ_HOST
# - name: NO_SQL_HOST
#   valueFrom:
#     secretKeyRef:
#       name: aws-secrets
#       key: LTSCALE_DEV_NO_SQL_HOST
# - name: DATABASE_NAME
#   value: "compliancexdb"
# - name: DATABASE_HOST
#   value: "10.0.4.21"
# - name: NO_SQL_ROUTER_NAME
#   value: "mongo_db"
# - name: NO_SQL_DATABASE_NAME
#   value: "compliancexdb"

# - name: REPORTS_BUCKET
#   value: "059516066038-export-logs-bucket"
# - name: ATTACHMENT_BUCKET
#   value: "059516066038-compliancex-ticketing-attachment"
# - name: IDP_URL
#   value: "https://idp.app.litmusscale.com"
*/